/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.1 */

#ifndef PB_MYOBJECT_CONFIG_PB_H_INCLUDED
#define PB_MYOBJECT_CONFIG_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

#ifdef __cplusplus
extern "C" {
#endif

/* Struct definitions */
typedef struct _myobject_Downlink {
    uint32_t start_hour;
    uint32_t end_hour;
} myobject_Downlink;


/* Initializer values for message structs */
#define myobject_Downlink_init_default           {0, 0}
#define myobject_Downlink_init_zero              {0, 0}

/* Field tags (for use in manual encoding/decoding) */
#define myobject_Downlink_start_hour_tag         1
#define myobject_Downlink_end_hour_tag           2

/* Struct field encoding specification for nanopb */
#define myobject_Downlink_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   start_hour,        1) \
X(a, STATIC,   SINGULAR, UINT32,   end_hour,          2)
#define myobject_Downlink_CALLBACK NULL
#define myobject_Downlink_DEFAULT NULL

extern const pb_msgdesc_t myobject_Downlink_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define myobject_Downlink_fields &myobject_Downlink_msg

/* Maximum encoded size of messages (where known) */
#define myobject_Downlink_size                   12

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
