// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: format.proto

#include "format.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// This is a temporary google only hack
#ifdef GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
#include "third_party/protobuf/version.h"
#endif
// @@protoc_insertion_point(includes)

namespace myobject {
class UplinkDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<Uplink>
      _instance;
} _Uplink_default_instance_;
}  // namespace myobject
namespace protobuf_format_2eproto {
static void InitDefaultsUplink() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::myobject::_Uplink_default_instance_;
    new (ptr) ::myobject::Uplink();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::myobject::Uplink::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<0> scc_info_Uplink =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 0, InitDefaultsUplink}, {}};

void InitDefaults() {
  ::google::protobuf::internal::InitSCC(&scc_info_Uplink.base);
}

::google::protobuf::Metadata file_level_metadata[1];

const ::google::protobuf::uint32 TableStruct::offsets[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::myobject::Uplink, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::myobject::Uplink, co2_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::myobject::Uplink, temperature_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::myobject::Uplink, humidity_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::myobject::Uplink, loudness_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::myobject::Uplink, battery_),
};
static const ::google::protobuf::internal::MigrationSchema schemas[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, sizeof(::myobject::Uplink)},
};

static ::google::protobuf::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::google::protobuf::Message*>(&::myobject::_Uplink_default_instance_),
};

void protobuf_AssignDescriptors() {
  AddDescriptors();
  AssignDescriptors(
      "format.proto", schemas, file_default_instances, TableStruct::offsets,
      file_level_metadata, NULL, NULL);
}

void protobuf_AssignDescriptorsOnce() {
  static ::google::protobuf::internal::once_flag once;
  ::google::protobuf::internal::call_once(once, protobuf_AssignDescriptors);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_PROTOBUF_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::internal::RegisterAllTypes(file_level_metadata, 1);
}

void AddDescriptorsImpl() {
  InitDefaults();
  static const char descriptor[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
      "\n\014format.proto\022\010myobject\"_\n\006Uplink\022\013\n\003co"
      "2\030\001 \001(\002\022\023\n\013temperature\030\002 \001(\002\022\020\n\010humidity"
      "\030\003 \001(\002\022\020\n\010loudness\030\004 \001(\002\022\017\n\007battery\030\005 \001("
      "\005b\006proto3"
  };
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
      descriptor, 129);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "format.proto", &protobuf_RegisterTypes);
}

void AddDescriptors() {
  static ::google::protobuf::internal::once_flag once;
  ::google::protobuf::internal::call_once(once, AddDescriptorsImpl);
}
// Force AddDescriptors() to be called at dynamic initialization time.
struct StaticDescriptorInitializer {
  StaticDescriptorInitializer() {
    AddDescriptors();
  }
} static_descriptor_initializer;
}  // namespace protobuf_format_2eproto
namespace myobject {

// ===================================================================

void Uplink::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int Uplink::kCo2FieldNumber;
const int Uplink::kTemperatureFieldNumber;
const int Uplink::kHumidityFieldNumber;
const int Uplink::kLoudnessFieldNumber;
const int Uplink::kBatteryFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

Uplink::Uplink()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  ::google::protobuf::internal::InitSCC(
      &protobuf_format_2eproto::scc_info_Uplink.base);
  SharedCtor();
  // @@protoc_insertion_point(constructor:myobject.Uplink)
}
Uplink::Uplink(const Uplink& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::memcpy(&co2_, &from.co2_,
    static_cast<size_t>(reinterpret_cast<char*>(&battery_) -
    reinterpret_cast<char*>(&co2_)) + sizeof(battery_));
  // @@protoc_insertion_point(copy_constructor:myobject.Uplink)
}

void Uplink::SharedCtor() {
  ::memset(&co2_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&battery_) -
      reinterpret_cast<char*>(&co2_)) + sizeof(battery_));
}

Uplink::~Uplink() {
  // @@protoc_insertion_point(destructor:myobject.Uplink)
  SharedDtor();
}

void Uplink::SharedDtor() {
}

void Uplink::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ::google::protobuf::Descriptor* Uplink::descriptor() {
  ::protobuf_format_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_format_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const Uplink& Uplink::default_instance() {
  ::google::protobuf::internal::InitSCC(&protobuf_format_2eproto::scc_info_Uplink.base);
  return *internal_default_instance();
}


void Uplink::Clear() {
// @@protoc_insertion_point(message_clear_start:myobject.Uplink)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::memset(&co2_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&battery_) -
      reinterpret_cast<char*>(&co2_)) + sizeof(battery_));
  _internal_metadata_.Clear();
}

bool Uplink::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:myobject.Uplink)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // float co2 = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(13u /* 13 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   float, ::google::protobuf::internal::WireFormatLite::TYPE_FLOAT>(
                 input, &co2_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // float temperature = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(21u /* 21 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   float, ::google::protobuf::internal::WireFormatLite::TYPE_FLOAT>(
                 input, &temperature_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // float humidity = 3;
      case 3: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(29u /* 29 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   float, ::google::protobuf::internal::WireFormatLite::TYPE_FLOAT>(
                 input, &humidity_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // float loudness = 4;
      case 4: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(37u /* 37 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   float, ::google::protobuf::internal::WireFormatLite::TYPE_FLOAT>(
                 input, &loudness_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // int32 battery = 5;
      case 5: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(40u /* 40 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &battery_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:myobject.Uplink)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:myobject.Uplink)
  return false;
#undef DO_
}

void Uplink::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:myobject.Uplink)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // float co2 = 1;
  if (this->co2() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteFloat(1, this->co2(), output);
  }

  // float temperature = 2;
  if (this->temperature() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteFloat(2, this->temperature(), output);
  }

  // float humidity = 3;
  if (this->humidity() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteFloat(3, this->humidity(), output);
  }

  // float loudness = 4;
  if (this->loudness() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteFloat(4, this->loudness(), output);
  }

  // int32 battery = 5;
  if (this->battery() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(5, this->battery(), output);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:myobject.Uplink)
}

::google::protobuf::uint8* Uplink::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:myobject.Uplink)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // float co2 = 1;
  if (this->co2() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteFloatToArray(1, this->co2(), target);
  }

  // float temperature = 2;
  if (this->temperature() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteFloatToArray(2, this->temperature(), target);
  }

  // float humidity = 3;
  if (this->humidity() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteFloatToArray(3, this->humidity(), target);
  }

  // float loudness = 4;
  if (this->loudness() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteFloatToArray(4, this->loudness(), target);
  }

  // int32 battery = 5;
  if (this->battery() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(5, this->battery(), target);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:myobject.Uplink)
  return target;
}

size_t Uplink::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:myobject.Uplink)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  // float co2 = 1;
  if (this->co2() != 0) {
    total_size += 1 + 4;
  }

  // float temperature = 2;
  if (this->temperature() != 0) {
    total_size += 1 + 4;
  }

  // float humidity = 3;
  if (this->humidity() != 0) {
    total_size += 1 + 4;
  }

  // float loudness = 4;
  if (this->loudness() != 0) {
    total_size += 1 + 4;
  }

  // int32 battery = 5;
  if (this->battery() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->battery());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void Uplink::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:myobject.Uplink)
  GOOGLE_DCHECK_NE(&from, this);
  const Uplink* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const Uplink>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:myobject.Uplink)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:myobject.Uplink)
    MergeFrom(*source);
  }
}

void Uplink::MergeFrom(const Uplink& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:myobject.Uplink)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.co2() != 0) {
    set_co2(from.co2());
  }
  if (from.temperature() != 0) {
    set_temperature(from.temperature());
  }
  if (from.humidity() != 0) {
    set_humidity(from.humidity());
  }
  if (from.loudness() != 0) {
    set_loudness(from.loudness());
  }
  if (from.battery() != 0) {
    set_battery(from.battery());
  }
}

void Uplink::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:myobject.Uplink)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void Uplink::CopyFrom(const Uplink& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:myobject.Uplink)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Uplink::IsInitialized() const {
  return true;
}

void Uplink::Swap(Uplink* other) {
  if (other == this) return;
  InternalSwap(other);
}
void Uplink::InternalSwap(Uplink* other) {
  using std::swap;
  swap(co2_, other->co2_);
  swap(temperature_, other->temperature_);
  swap(humidity_, other->humidity_);
  swap(loudness_, other->loudness_);
  swap(battery_, other->battery_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
}

::google::protobuf::Metadata Uplink::GetMetadata() const {
  protobuf_format_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_format_2eproto::file_level_metadata[kIndexInFileMessages];
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace myobject
namespace google {
namespace protobuf {
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::myobject::Uplink* Arena::CreateMaybeMessage< ::myobject::Uplink >(Arena* arena) {
  return Arena::CreateInternal< ::myobject::Uplink >(arena);
}
}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)
