// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: config.proto

package iot.sensor;

public final class Config {
  private Config() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface DownlinkOrBuilder extends
      // @@protoc_insertion_point(interface_extends:myobject.Downlink)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>uint32 start_hour = 1;</code>
     * @return The startHour.
     */
    int getStartHour();

    /**
     * <code>uint32 end_hour = 2;</code>
     * @return The endHour.
     */
    int getEndHour();
  }
  /**
   * Protobuf type {@code myobject.Downlink}
   */
  public static final class Downlink extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:myobject.Downlink)
      DownlinkOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Downlink.newBuilder() to construct.
    private Downlink(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Downlink() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Downlink();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Downlink(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              startHour_ = input.readUInt32();
              break;
            }
            case 16: {

              endHour_ = input.readUInt32();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return iot.sensor.Config.internal_static_myobject_Downlink_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return iot.sensor.Config.internal_static_myobject_Downlink_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              iot.sensor.Config.Downlink.class, iot.sensor.Config.Downlink.Builder.class);
    }

    public static final int START_HOUR_FIELD_NUMBER = 1;
    private int startHour_;
    /**
     * <code>uint32 start_hour = 1;</code>
     * @return The startHour.
     */
    @java.lang.Override
    public int getStartHour() {
      return startHour_;
    }

    public static final int END_HOUR_FIELD_NUMBER = 2;
    private int endHour_;
    /**
     * <code>uint32 end_hour = 2;</code>
     * @return The endHour.
     */
    @java.lang.Override
    public int getEndHour() {
      return endHour_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (startHour_ != 0) {
        output.writeUInt32(1, startHour_);
      }
      if (endHour_ != 0) {
        output.writeUInt32(2, endHour_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (startHour_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(1, startHour_);
      }
      if (endHour_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(2, endHour_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof iot.sensor.Config.Downlink)) {
        return super.equals(obj);
      }
      iot.sensor.Config.Downlink other = (iot.sensor.Config.Downlink) obj;

      if (getStartHour()
          != other.getStartHour()) return false;
      if (getEndHour()
          != other.getEndHour()) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + START_HOUR_FIELD_NUMBER;
      hash = (53 * hash) + getStartHour();
      hash = (37 * hash) + END_HOUR_FIELD_NUMBER;
      hash = (53 * hash) + getEndHour();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static iot.sensor.Config.Downlink parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static iot.sensor.Config.Downlink parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static iot.sensor.Config.Downlink parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static iot.sensor.Config.Downlink parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static iot.sensor.Config.Downlink parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static iot.sensor.Config.Downlink parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static iot.sensor.Config.Downlink parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static iot.sensor.Config.Downlink parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static iot.sensor.Config.Downlink parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static iot.sensor.Config.Downlink parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static iot.sensor.Config.Downlink parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static iot.sensor.Config.Downlink parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(iot.sensor.Config.Downlink prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code myobject.Downlink}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:myobject.Downlink)
        iot.sensor.Config.DownlinkOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return iot.sensor.Config.internal_static_myobject_Downlink_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return iot.sensor.Config.internal_static_myobject_Downlink_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                iot.sensor.Config.Downlink.class, iot.sensor.Config.Downlink.Builder.class);
      }

      // Construct using iot.sensor.Config.Downlink.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        startHour_ = 0;

        endHour_ = 0;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return iot.sensor.Config.internal_static_myobject_Downlink_descriptor;
      }

      @java.lang.Override
      public iot.sensor.Config.Downlink getDefaultInstanceForType() {
        return iot.sensor.Config.Downlink.getDefaultInstance();
      }

      @java.lang.Override
      public iot.sensor.Config.Downlink build() {
        iot.sensor.Config.Downlink result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public iot.sensor.Config.Downlink buildPartial() {
        iot.sensor.Config.Downlink result = new iot.sensor.Config.Downlink(this);
        result.startHour_ = startHour_;
        result.endHour_ = endHour_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof iot.sensor.Config.Downlink) {
          return mergeFrom((iot.sensor.Config.Downlink)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(iot.sensor.Config.Downlink other) {
        if (other == iot.sensor.Config.Downlink.getDefaultInstance()) return this;
        if (other.getStartHour() != 0) {
          setStartHour(other.getStartHour());
        }
        if (other.getEndHour() != 0) {
          setEndHour(other.getEndHour());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        iot.sensor.Config.Downlink parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (iot.sensor.Config.Downlink) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int startHour_ ;
      /**
       * <code>uint32 start_hour = 1;</code>
       * @return The startHour.
       */
      @java.lang.Override
      public int getStartHour() {
        return startHour_;
      }
      /**
       * <code>uint32 start_hour = 1;</code>
       * @param value The startHour to set.
       * @return This builder for chaining.
       */
      public Builder setStartHour(int value) {
        
        startHour_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint32 start_hour = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearStartHour() {
        
        startHour_ = 0;
        onChanged();
        return this;
      }

      private int endHour_ ;
      /**
       * <code>uint32 end_hour = 2;</code>
       * @return The endHour.
       */
      @java.lang.Override
      public int getEndHour() {
        return endHour_;
      }
      /**
       * <code>uint32 end_hour = 2;</code>
       * @param value The endHour to set.
       * @return This builder for chaining.
       */
      public Builder setEndHour(int value) {
        
        endHour_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint32 end_hour = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearEndHour() {
        
        endHour_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:myobject.Downlink)
    }

    // @@protoc_insertion_point(class_scope:myobject.Downlink)
    private static final iot.sensor.Config.Downlink DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new iot.sensor.Config.Downlink();
    }

    public static iot.sensor.Config.Downlink getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Downlink>
        PARSER = new com.google.protobuf.AbstractParser<Downlink>() {
      @java.lang.Override
      public Downlink parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Downlink(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Downlink> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Downlink> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public iot.sensor.Config.Downlink getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_myobject_Downlink_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_myobject_Downlink_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014config.proto\022\010myobject\"0\n\010Downlink\022\022\n\n" +
      "start_hour\030\001 \001(\r\022\020\n\010end_hour\030\002 \001(\rB\014\n\nio" +
      "t.sensorb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_myobject_Downlink_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_myobject_Downlink_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_myobject_Downlink_descriptor,
        new java.lang.String[] { "StartHour", "EndHour", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
